Ecommerce/ViewModels/SignInViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Ecommerce.ViewModels
{
    public class SignInViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Enter Email") ,  DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required(ErrorMessage ="Enter Password") , DataType(DataType.Password)]
        public string Password { get; set; }

    }
}

Ecommerce/ViewModels/SignUpUserModel.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
namespace Ecommerce.Models
{
    public class SignUpUserModel : User    
    {
        //public int Id { get; set; }

        //[Required(ErrorMessage = "ادخل الايميل بشكل صحيح")]
        //[Display(Name = "البريد الالكتروني")]
        //[DataType(DataType.EmailAddress)]
        //public string Email { get; set; }

        //[Required(ErrorMessage = "ادخل كلمة المرور")]
        //[Display(Name = "كلمة المرور")]
        //[DataType(DataType.Password)]
        //[Compare("ConfirmPassword", ErrorMessage = "كلمة المرور غير متطابقة")]
        //public string password { get; set; }

        //[Required(ErrorMessage = "اعد كتابة كلمة المرور")]
        //[Display(Name = "تاكيد كلمة المرور")]
        //[DataType(DataType.Password)]
        //public string ConfirmPassword { get; set; }

        //[Required(ErrorMessage = "اكتب العنوان")]
        //[Display(Name = "العنوان")]
        //[DataType(DataType.Text)]
        //public string Address { get; set; }

        //[Required(ErrorMessage = "ادخل المدينة")]
        //[Display(Name = "المدينة")]
        //[DataType(DataType.Text)]
        //public string City { get; set; }

        //[Required(ErrorMessage = "ادخل Zip code")]
        //[Display(Name = "الرمز البريدي")]
        //[DataType(DataType.PostalCode)]
        //public int ZipCode { get; set; }

        //[Required(ErrorMessage = "ادخل رقم الهاتف المحمول")]
        //[Display(Name = "رقم الهاتف المحمول")]
        //[DataType(DataType.PhoneNumber)]
        //public int Modile { get; set; }

        //public bool RememberMe { get; set; }
    }
}

Ecommerce/Areas/Admin/Controllers/DashBoardController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Ecommerce.Areas.Admin.Controllers
{
    //[Authorize(Roles = "Admin")]
  
    [Route("dashboard")]
    public class DashBoardController : Controller
    {
        public AdminAuth AdminAuth { get; set; }

       
        public ViewResult Index()
        {
            return View("~/Areas/Admin/Views/Dashboard/index.cshtml");
        }

        
        public async Task<IActionResult> AdminLogin(string returnUrl)
        {
            if (!ModelState.IsValid) return View();
            {
                if (AdminAuth.username == "admin" && AdminAuth.password == "admin")
                    return View("Dashboard" , "Index");
            }
            var authenticationProperties = new AuthenticationProperties()
            {
                IsPersistent = AdminAuth.RememberMe
            };

            var claim = new List<Claim>
            {
                new Claim(AdminAuth.username , "admin"),
                new Claim(AdminAuth.password , "admin")
            };

            var idntity = new ClaimsIdentity(claim ,CookieAuthenticationDefaults.AuthenticationScheme);
            var prenciple = new ClaimsPrincipal(idntity);

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, prenciple , authenticationProperties);

            if (string.IsNullOrEmpty(returnUrl))
            {
                return RedirectToAction("Index", "Home");
            }

            return RedirectToAction("index", "Dashboard");
        }

       
    }
    public class AdminAuth
    {
        [Display(Name ="Admin username")]
        [Required]
        public string username { get; set; } = "admin"; 

        [Display(Name = "Password")]
        [Required]
        public string password { get; set; } = "admin";    

        public bool  RememberMe { get; set; }

    }
}

Ecommerce/Controllers/AccountController.cs
using Ecommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using System;
using System.Threading.Tasks;

namespace Ecommerce.Controllers
{
    public class AccountController : Controller
    {
       
       
        [HttpGet]
        [Route("signup")]
        [Alloanoymous]
        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        [Route("signup")]
        public IActionResult SignUp(SignUpUserModel model)
        {
            if (ModelState.IsValid)
            {
                //
                ModelState.Clear();

            }
            return View(model); 
        }
        [Authorize]
        public IActionResult SignIn()
        {
           return View();
        }
        [Authorize]
        [Route("Profile")]
        public IActionResult Profile()
        {
            return View();
        }

    }
    

    internal class AlloanoymousAttribute : Attribute
    {
    }
}

Ecommerce/Controllers/HomeController.cs
using Ecommerce.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Ecommerce.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Ecommerce/Areas/Admin/Views/DashBoard/AdminLogin.cshtml
@model Ecommerce.Areas.Admin.Controllers.AdminAuth
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "AdminLogin";
    Layout = "~/Areas/Admin/Shared/_AdminLayout.cshtml";
}

<h2>Login</h2>


<hr />
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <form method="post" asp-area="Admin" asp-controller="DashBoard" asp-action="Adminlogin">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="username" class="control-label"></label>
                    <input asp-for="username" class="form-control" />

                </div>
                <div class="form-group">
                    <label asp-for="password" class="control-label"></label>
                    <input asp-for="password" class="form-control" />

                </div>
                <div class="form-check-inline">
                    <label class="form-check-label" asp-for="RememberMe">remmeber me</label>
                    <input class="form-check-input" asp-for="RememberMe" />
                </div>
                <div class="form-group">
                    <input type="submit" asp-route="Dashboard" asp-action="index" value="Login" class="btn btn-outline-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Ecommerce/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}           <!--Free Shipping Baner-->
           <div class=container>
                 <div class="row ">
               <div class="mt-2 bg-danger fs-3 text-white text-center ">
                 <P>شحن مجاني عندما يبلغ مجموع مشرياتك 375 ريال وخصم اضافي 10% لأول 50 عملية شراء</P>
               </div>
             </div>
           </div>

<div class="container mt-3">
       <div class="row">
           <div class="col-xl-12 col-md-12 col-sm-12">
              <id id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
              <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
                  aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                </div>
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img src="~/user/img/ar_slider-01.png" class="d-block w-100" alt="...">
                  </div>
                  <div class="carousel-item">
                    <img src="~/user/img/ar_slider-02.png" class="d-block w-100" alt="...">
                  </div>
                  <div class="carousel-item">
                    <img src="~/user/img/ar_slider-03.png" class="d-block w-100" alt="...">
                  </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              </id>
            </div>
          </div>
  </div>
   <!-- cards -->
   <div class="container">
     <div class="row mt-3">
       <div class="col-sm-3">
          <partial name="_ProductCardsPartial" />
      </div>
     <div class="col-sm-3">
       <partial name="_ProductCardsPartial" />
    </div>
   <div class="col-sm-3">
       <partial name="_ProductCardsPartial" />
   </div>
   <div class="col-sm-3">
        <partial name="_ProductCardsPartial" />
   </div>
  </div>
 </div>

Ecommerce/Views/Shared/_FooterPartial.cshtml
 <div class="container mt-2 mb-2">       
    <footer class="bg-dark text-center text-white">
     <div class="container p-4 pb-0">
      <section class="mb-4">
         <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-facebook-f"></i></a>
         <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-twitter"></i></a>
         <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-google"></i></a>
         <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-instagram"></i></a>
         <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-linkedin-in"></i></a>
         <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-github"></i></a>
      </section>
  </div>
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">© 2020 Copyright:<a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
 
</footer>
</div>

Ecommerce/Views/Shared/_HeaderPartial.cshtml
 <header class="container shadow-lg">
      <nav class="navbar navbar-expand-md ">
          <a class="navbar-brand" asp-controller="Home" asp-action="index">
              <img style="max-width: 100px ; max-height: 60px" src="~/user/img/logo.png" alt=""
                   srcset="">
          </a>
             <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
               aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
             </button>
                      <div class="collapse navbar-collapse " id="navbarSupportedContent">
                        <div class="input-group input-group rounded mx-2" style="width: 20rem;">
                          <input type="search" class="form-control rounded" placeholder="اكتشف المنتجات" aria-label="Search"
                            aria-describedby="search-addon" />
                          <span class="input-group-text border-0" id="search-addon">
                            <i class="fas fa-search"></i>
                          </span>
                        </div>
                      </div>
                      <div class="row  justify-content-end d-flex ">
                        
                          <div class="col-sm-12 col-md-12 gap-2 d-inline-flex">
                              <ul class="navbar-nav">
                                  <li class="nav-item">
                                      <a class="nav-link text-dark " asp-area="identity" asp-page="/account/login">دخول </a>
                                  </li>
                                  <li class="nav-item">
                                      <a class="nav-link text-dark" asp-area="identity" asp-page="/account/Register">تسجيل</a>
                                  </li>
                                 
                              </ul>
                              <!--====================== My Account Dropdowen ===================================================-->
                              <div class="dropdown ">
                                  <button class="btn btn-warning dropdown-toggle d-block btn-lg" type="button" id="triggerId" data-bs-toggle="dropdown" aria-haspopup="true"
                                          aria-expanded="false">
                                      حسابي
                                  </button>
                                  <div class="dropdown-menu float-start" aria-labelledby="triggerId">
                                      <a class="dropdown-item" href="#"><i class="fas fa-list"></i> الطلبات</a>
                                      <a class="dropdown-item " href="#"><i class="fas fa-address-book"></i> العناوين</a>
                                      <a class="dropdown-item " href="#"><i class="fas fa-dollar-sign"></i> عمليات الدفع</a>
                                      <a class="dropdown-item " href="#"><i class="fas fa-undo"></i> الارجاع</a>
                                      <a class="dropdown-item " href="#">طلبات الضمان</a>
                                      <a class="dropdown-item " href="#">تفضيلات</a>
                                      <a class="dropdown-item " href="#">حسابي</a>

                                      <div class="dropdown-divider"></div>
                                      <a class="dropdown-item" href="#">تسجيل خروج</a>
                                  </div>
                              </div>
                              <a type="button" asp-controller="Account" asp-action="Profile" class="btn btn-info">سلة التسوق<i class="fas fa-shopping-cart"></i></a>
                          </div>      
                    </div>
                      </nav>

                      <!-- Free Shipping Ads -->
              <div class="row">
                    <div class="navbar navbar-expand-sm navbar-dark bg-dark">
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                          data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                          aria-label="Toggle navigation">
                          <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav align-content-end">
                      <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">رجالي</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">نسائي</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">بنات</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">اولاد</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">اكسسوارات</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">الاكترونيات</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">الاكترونيات</a>
                            </li>
                            </ul>
                     </div>
                  </div>
                  </div>
             
           
    </header>
    

Ecommerce/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ecommerce</title>
    <!--Bootstrap 5 Dicret Link-->
    <link rel="stylesheet" href="~/user/css/bootstrap.css">
    <link rel="stylesheet" href=~/user/css/bootstrap.min.css />
    <link rel="stylesheet" href="~/user/css/all.css">
    <link rel="stylesheet" href="~/user/css/site.css">

    <!---->

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>الصفحة الرئيسية</title>
</head>

<body dir="rtl">
    <header class="container shadow-lg">
        <nav class="navbar navbar-expand-md ">
            <a class="navbar-brand" asp-controller="Home" asp-action="index">
                <img style="max-width: 100px ; max-width:40px" src="~/user/img/logo.png" alt=""
                     srcset="">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse " id="navbarSupportedContent">
                <div class="input-group input-group rounded mx-2" style="width: 20rem;">
                    <input type="search" class="form-control rounded" placeholder="اكتشف المنتجات" aria-label="Search"
                           aria-describedby="search-addon" />
                    <span class="input-group-text border-0" id="search-addon">
                        <i class="fas fa-search"></i>
                    </span>
                </div>
            </div>
        </nav>       
    </header>
             
             @RenderBody()

  <div class="container mt-2 mb-2">       
    <footer class="bg-dark text-center text-white">
     <div class="container p-4 pb-0">
      <section class="mb-4">
         <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-facebook-f"></i></a>
         <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-twitter"></i></a>
         <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-google"></i></a>
         <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-instagram"></i></a>
         <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-linkedin-in"></i></a>
         <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-github"></i></a>
      </section>
  </div>
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">© 2020 Copyright:<a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
 
</footer>
</div>

         @await RenderSectionAsync("Scripts", required: false)
  
</body>
</html>

Ecommerce/Views/Shared/_ProductCardsPartial.cshtml
 <div class="card">
           <img src="~/user/img/solar.jpg" class="card-img-top" alt="...">
             <div class="card-body mx-2">
                 <h5 class="card-title text-center text-white mx-2">العرض الاول</h5>
                 <p class="card-text mx-2"> <i class="far fa-arrow-alt-circle-left mx-2"></i> 8 كيلو واط </p>
                 <p class="card-text mx-2"> <i class="far fa-arrow-alt-circle-left mx-2"></i> لوحة24 </p>
                 <p class="card-text mx-2"> <i class="far fa-arrow-alt-circle-left mx-2"></i> المنظم </p>
                 <p class="card-text mx-2"> <i class="far fa-arrow-alt-circle-left mx-2"></i> شاملة التركيب </p>
                 <p class="card-text text-center text-white fs-5 pt-2"> SAR 34,900 (شاملة الضريبة) </p>
         
         <div class="btn-block">
              <a href="#" class="btn btn-warning align-content-sm-center   btn-toolbar mx-auto ">  شراء </a>
         </div>
       </div>
     </div>

Ecommerce/Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ecommerce</title>
    <!--Bootstrap 5 Dicret Link-->
    <link rel="stylesheet" href="~/user/css/bootstrap.css">
    <link rel="stylesheet" href=~/user/css/bootstrap.min.css />
    <link rel="stylesheet" href="~/user/css/all.css">
    <link rel="stylesheet" href="~/user/css/site.css">



    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>الصفحة الرئيسية</title>
</head>

<body dir="rtl">

      <partial name="_HeaderPartial" />
    
             @RenderBody()
  
      <partial name="_FooterPartial" />

    @await RenderSectionAsync("Scripts", required: false)  
  
</body>
</html>